from typing import Protocol, Any
from collections.abc import AsyncIterable
from pathlib import Path
from datetime import datetime
from sqlalchemy import Row
from src.models.domain_model import ForecastModel, BotUserModel, BotUserStateModel
from src.models.enums import Commands, UserLocationState


class ETLQueryProtocol(Protocol):
    async def get_forecast_by_range(
        self, adm4_code: str, datetime_range: tuple[datetime, datetime]
    ) -> AsyncIterable[Row[Any]]: ...


class BotQueryProtocol(Protocol):
    async def get_bot_offset(self, bot_token: str) -> Row[Any] | None: ...
    async def insert_or_update_bot_offset(
        self, bot_token: str, offset: int, update_time: datetime
    ) -> None: ...
    async def get_user(self, chat_id: int) -> Row[Any] | None: ...
    async def insert_or_update_user(self, user_data: BotUserModel) -> None: ...
    async def get_user_state(self, chat_id: int) -> Row[Any] | None: ...
    async def insert_or_update_user_state(
        self, user_state_data: BotUserStateModel
    ) -> None: ...


class LocationFinderProtocol(Protocol):
    async def search_city_or_regency(self, city_or_regency: str) -> list[str]: ...
    async def search_subdistrict(self, city_or_regency: str) -> list[str]: ...
    async def search_village(
        self, city_or_regency: str, subdistrict: str
    ) -> list[str]: ...
    async def get_adm4_code(
        self, city_or_regency: str, subdistrict: str, village: str
    ) -> str: ...
    async def start_csv_to_local_db_transformation(
        self, csv_filepath: Path
    ) -> None: ...


class BotServiceProtocol(Protocol):
    async def create_or_update_user(self, user: BotUserModel) -> None: ...
    async def get_user(self, chat_id: int) -> BotUserModel | None: ...
    async def check_user_location_state(self, chat_id: int) -> UserLocationState: ...
    async def create_or_update_user_state(
        self, user_state: BotUserStateModel
    ) -> None: ...
    async def get_user_state(self, chat_id: int) -> BotUserStateModel | None: ...
    def get_today_weather_forecast(
        self, adm4_code: str
    ) -> AsyncIterable[ForecastModel]: ...
    def get_tomorrow_weather_forecast(
        self, adm4_code: str
    ) -> AsyncIterable[ForecastModel]: ...


class LocationServiceProtocol(Protocol):
    async def search_city_or_regency(self, name_like: str) -> list[str]: ...
    async def search_subdistrict(self, exact_name: str) -> list[str]: ...
    async def search_village(self, exact_name: str) -> list[str]: ...
    async def compare_input_with_query_result(
        self, input: str, query_result: list[str]
    ) -> None: ...
    async def get_adm4_code_from_user_state(self, chat_id: int) -> str: ...


class BotStateHandlerProtocol(Protocol):
    async def get_offset(self, bot_token: str) -> int | None: ...
    async def store_offset(self, bot_token: str, offset: int) -> None: ...


class BotRespondHandlerProtocol(Protocol):
    async def parse_command(
        self, chat_id: int, command: Commands, input_value: str | None = None
    ) -> str: ...
